version: '3'

services:
  spigot-server:
    image: ranvier/spigot-mc:1.14.4

    container_name: spigot-server
    restart: always

    ports:
      - '25565:25565'  # Server Port
      - '25575:25575'  # RCON Port
    volumes:
      - './data:/data'
